name: Hubot Slack Adapter CI Builds
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20.x]
        hubot-version: ['11.1.9']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
        npm install hubot@"${{ matrix.hubot-version }}"
    - name: Run tests
      run: |
        npm test
